#!/usr/bin/env bash
set -e

OS=$(cat /etc/os-release | grep "^ID=" | sed -e 's/ID=//' | sed -e 's/"//')
[ "$OS" != "ubuntu" ] && echo "Not a Ubuntu system; quiting" && exit 1

sudo apt -y update
sudo apt -y upgrade

sudo apt -y install curl
sudo apt -y install make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
      libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

sudo apt install -y --no-install-recommends pipx git ca-certificates python3 python3-venv \
    libgl1 libxkbcommon-x11-0 libegl1-mesa libfontconfig1 libglib2.0-0 libdbus-1-3 \
    libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libnss3 libxcomposite1 \
    libxdamage1 libxrender1 libxrandr2 libxtst6 libxi6 libasound2

sudo add-apt-repository -y ppa:aslatter/ppa
sudo apt install -y awesome awesome-extra scrot blueman \
  xfce4-power-manager xbacklight xcompmgr alacritty mpv suckless-tools

sudo apt-add-repository -y ppa:fish-shell/release-3
sudo apt install -y fish direnv

sudo add-apt-repository -y ppa:neovim-ppa/unstable
sudo apt install -y xsel neovim lua5.1 ninja-build npm

sudo apt install -y pass xdotool xsel pinentry-gnome3
