#!/usr/bin/env bash
set -e

clone copycat-killer/lain $HOME/.config/awesome/lain

sudo mkdir -p /root/.icons/default /root/.config/gtk-3.0
sudo cp ~/.icons/default/index.theme /root/.icons/default/
sudo cp ~/.config/gtk-3.0/settings.ini /root/.config/gtk-3.0/
fc-cache -f -v
