#!/usr/bin/env bash
set -e

git clone git@github.com:pyenv/pyenv $HOME/.pyenv || true

pushd ~/.pyenv
git reset --hard
git pull
popd

[[ "$PATH" != *"$HOME/.pyenv/bin"* ]] && export PATH=$PATH:$HOME/.pyenv/bin

PATH=$PATH:$HOME/.pyenv/bin

versions=()
for idx in $(seq 12 -1 9); do
  version=$(pyenv install -l | tr -d " " | grep "^3.$idx.[[:digit:]]\\+$" | tail -1)
  versions+=($version)
  echo pyenv install $version
done
echo pyenv global ${versions[@]}

mkdir -p $HOME/.venv
