#!/usr/bin/env bash
set -e

clone https://github.com/pyenv/pyenv $HOME/.pyenv || true

pushd ~/.pyenv
git reset --hard
git pull
popd

PYTHON=python
python3 --version >/dev/null && PYTHON=python3
[ -z "$(which $PYTHON)" ] && echo "python missing" && exit 1

MINOR=$($PYTHON -c "import sys; print(sys.version_info.minor)")
NVIM_VENV=$HOME/.venv/nvim/3${MINOR}
[ ! -d $NVIM_VENV ] && $PYTHON -m venv $NVIM_VENV

NVIM_PIP=$NVIM_VENV/bin/pip
$NVIM_PIP install -Ur $HOME/.config/requirements.txt
$NVIM_PIP install neovim-remote
