#!/usr/bin/env bash
set -e

OS=$(cat /etc/os-release | grep "^ID=" | sed -e 's/ID=//' | sed -e 's/"//')
[ "$OS" != "arch" ] && echo "Not a Arch system; quiting" && exit 1

mkdir ~/source/yay

# Ensure installed
if ! command -v yay -v >/dev/null 2>&1; then
  pacman --noconfirm -S git
  git clone https://aur.archlinux.org/yay.git ~/source/yay
fi
pushd ~/source/yay
git reset --hard
git pull
sudo makepkg --noconfirm -si
popd

# Start by speed checking mirror list
yay -Sy --noconfirm reflector
sudo reflector -l 5 --verbose --sort rate --save /etc/pacman.d/mirrorlist
yay -Syy --noconfirm
yay -Sc --noconfirm

yay -S --needed base-devel openssl zlib xz tk
yay -Sy --noconfirm qutebrowser lua5.1
yay -Sy --noconfirm awesome vicious lain xcompmgr \
  network-manager-applet scrot blueman powerline-fonts \
  xorg-xbacklight ttf-ubuntu-font-family \
  xtrlock lightdm-slick-greeter \
  lxappearance materia-gtk-theme alacritty-sixel \
  mpv

yay -Sy --noconfirm fish direnv
yay -Sy --noconfirm neovim-git xsel ninja npm
yay -Sy --noconfirm pass xdotool xsel
