[styles]
# 'none': Style(),
# 'reset': Style(
#     color=Color('default', ColorType.DEFAULT),
#     bgcolor=Color('default', ColorType.DEFAULT),
#     bold=False,
#     dim=False,
#     italic=False,
#     underline=False,
#     blink=False,
#     blink2=False,
#     reverse=False,
#     conceal=False,
#     strike=False
# ),
# 'dim': Style(dim=True),
# 'bright': Style(dim=False),
# 'bold': Style(bold=True),
# 'strong': Style(bold=True),
# 'code': Style(bold=True, reverse=True),
# 'italic': Style(italic=True),
# 'emphasize': Style(italic=True),
# 'underline': Style(underline=True),
# 'blink': Style(blink=True),
# 'blink2': Style(blink2=True),
# 'reverse': Style(reverse=True),
# 'strike': Style(strike=True),
# 'black': Style(color=Color('black', ColorType.STANDARD, number=0)),
# 'red': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'green': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'yellow': Style(color=Color('yellow', ColorType.STANDARD, number=3)),
# 'magenta': Style(color=Color('magenta', ColorType.STANDARD, number=5)),
# 'cyan': Style(color=Color('cyan', ColorType.STANDARD, number=6)),
# 'white': Style(color=Color('white', ColorType.STANDARD, number=7)),
# 'inspect.attr': Style(color=Color('yellow', ColorType.STANDARD, number=3), italic=True),
# 'inspect.attr.dunder': Style(color=Color('yellow', ColorType.STANDARD, number=3), dim=True, italic=True),
# 'inspect.callable': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'inspect.def': Style(color=Color('bright_cyan', ColorType.STANDARD, number=14), italic=True),
# 'inspect.error': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'inspect.equals': Style(),
# 'inspect.help': Style(color=Color('cyan', ColorType.STANDARD, number=6)),
# 'inspect.doc': Style(dim=True),
# 'inspect.value.border': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'live.ellipsis': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'layout.tree.row': Style(color=Color('red', ColorType.STANDARD, number=1), dim=False),
# 'layout.tree.column': Style(color=Color('blue', ColorType.STANDARD, number=4), dim=False),
# 'logging.keyword': Style(color=Color('yellow', ColorType.STANDARD, number=3), bold=True),
# 'logging.level.notset': Style(dim=True),
# 'logging.level.debug': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'logging.level.info': Style(color=Color('blue', ColorType.STANDARD, number=4)),
# 'logging.level.warning': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'logging.level.error': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'logging.level.critical': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True, reverse=True),
# 'log.level': Style(),
# 'log.time': Style(color=Color('cyan', ColorType.STANDARD, number=6), dim=True),
# 'log.message': Style(),
# 'log.path': Style(dim=True),
# 'repr.ellipsis': Style(color=Color('yellow', ColorType.STANDARD, number=3)),
# 'repr.indent': Style(color=Color('green', ColorType.STANDARD, number=2), dim=True),
# 'repr.error': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'repr.str': Style(color=Color('green', ColorType.STANDARD, number=2), bold=False, italic=False),
# 'repr.brace': Style(bold=True),
# 'repr.comma': Style(bold=True),
# 'repr.ipv4': Style(color=Color('bright_green', ColorType.STANDARD, number=10), bold=True),
# 'repr.ipv6': Style(color=Color('bright_green', ColorType.STANDARD, number=10), bold=True),
# 'repr.eui48': Style(color=Color('bright_green', ColorType.STANDARD, number=10), bold=True),
# 'repr.eui64': Style(color=Color('bright_green', ColorType.STANDARD, number=10), bold=True),
# 'repr.tag_start': Style(bold=True),
# 'repr.tag_name': Style(color=Color('bright_magenta', ColorType.STANDARD, number=13), bold=True),
# 'repr.tag_contents': Style(color=Color('default', ColorType.DEFAULT)),
# 'repr.tag_end': Style(bold=True),
# 'repr.attrib_name': Style(color=Color('yellow', ColorType.STANDARD, number=3), italic=False),
# 'repr.attrib_equal': Style(bold=True),
# 'repr.attrib_value': Style(color=Color('magenta', ColorType.STANDARD, number=5), italic=False),
# 'repr.number': Style(color=Color('cyan', ColorType.STANDARD, number=6), bold=True, italic=False),
# 'repr.bool_true': Style(color=Color('bright_green', ColorType.STANDARD, number=10), italic=True),
# 'repr.bool_false': Style(color=Color('bright_red', ColorType.STANDARD, number=9), italic=True),
# 'repr.none': Style(color=Color('magenta', ColorType.STANDARD, number=5), italic=True),
# 'repr.url': Style(color=Color('bright_blue', ColorType.STANDARD, number=12), bold=False, italic=False, underline=True),
# 'repr.uuid': Style(color=Color('bright_yellow', ColorType.STANDARD, number=11), bold=False),
# 'repr.call': Style(color=Color('magenta', ColorType.STANDARD, number=5), bold=True),
# 'repr.path': Style(color=Color('magenta', ColorType.STANDARD, number=5)),
# 'repr.filename': Style(color=Color('bright_magenta', ColorType.STANDARD, number=13)),
# 'rule.line': Style(color=Color('bright_green', ColorType.STANDARD, number=10)),
# 'rule.text': Style(),
# 'json.brace': Style(bold=True),
# 'json.bool_true': Style(color=Color('bright_green', ColorType.STANDARD, number=10), italic=True),
# 'json.bool_false': Style(color=Color('bright_red', ColorType.STANDARD, number=9), italic=True),
# 'json.null': Style(color=Color('magenta', ColorType.STANDARD, number=5), italic=True),
# 'json.number': Style(color=Color('cyan', ColorType.STANDARD, number=6), bold=True, italic=False),
# 'json.str': Style(color=Color('green', ColorType.STANDARD, number=2), bold=False, italic=False),
# 'json.key': Style(color=Color('blue', ColorType.STANDARD, number=4), bold=True),
# 'prompt': Style(),
# 'prompt.choices': Style(color=Color('magenta', ColorType.STANDARD, number=5), bold=True),
# 'prompt.default': Style(color=Color('cyan', ColorType.STANDARD, number=6), bold=True),
# 'prompt.invalid': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'prompt.invalid.choice': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'pretty': Style(),
# 'scope.border': Style(color=Color('blue', ColorType.STANDARD, number=4)),
# 'scope.key': Style(color=Color('yellow', ColorType.STANDARD, number=3), italic=True),
# 'scope.key.special': Style(color=Color('yellow', ColorType.STANDARD, number=3), dim=True, italic=True),
# 'scope.equals': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'table.header': Style(bold=True),
# 'table.footer': Style(bold=True),
# 'table.cell': Style(),
# 'table.title': Style(italic=True),
# 'table.caption': Style(dim=True, italic=True),
# 'traceback.error': Style(color=Color('red', ColorType.STANDARD, number=1), italic=True),
# 'traceback.border.syntax_error': Style(color=Color('bright_red', ColorType.STANDARD, number=9)),
# 'traceback.border': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'traceback.text': Style(),
# 'traceback.title': Style(color=Color('red', ColorType.STANDARD, number=1), bold=True),
# 'traceback.exc_type': Style(color=Color('bright_red', ColorType.STANDARD, number=9), bold=True),
# 'traceback.exc_value': Style(),
# 'traceback.offset': Style(color=Color('bright_red', ColorType.STANDARD, number=9), bold=True),
# 'bar.back': Style(color=Color('grey23', ColorType.EIGHT_BIT, number=237)),
# 'bar.complete': Style(color=Color('rgb(249,38,114)', ColorType.TRUECOLOR, triplet=ColorTriplet(red=249, green=38, blue=114))),
# 'bar.finished': Style(color=Color('rgb(114,156,31)', ColorType.TRUECOLOR, triplet=ColorTriplet(red=114, green=156, blue=31))),
# 'bar.pulse': Style(color=Color('rgb(249,38,114)', ColorType.TRUECOLOR, triplet=ColorTriplet(red=249, green=38, blue=114))),
# 'progress.description': Style(),
# 'progress.filesize': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'progress.filesize.total': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'progress.download': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'progress.elapsed': Style(color=Color('yellow', ColorType.STANDARD, number=3)),
# 'progress.percentage': Style(color=Color('magenta', ColorType.STANDARD, number=5)),
# 'progress.remaining': Style(color=Color('cyan', ColorType.STANDARD, number=6)),
# 'progress.data.speed': Style(color=Color('red', ColorType.STANDARD, number=1)),
# 'progress.spinner': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'status.spinner': Style(color=Color('green', ColorType.STANDARD, number=2)),
# 'tree': Style(),
# 'tree.line': Style(),
# 'markdown.paragraph': Style(),
# 'markdown.text': Style(),
# 'markdown.emph': Style(italic=True),
# 'markdown.strong': Style(bold=True),
# 'markdown.code': Style(color=Color('bright_white', ColorType.STANDARD, number=15), bgcolor=Color('black', ColorType.STANDARD, number=0)),
# 'markdown.code_block': Style(color=Color('cyan', ColorType.STANDARD, number=6), bgcolor=Color('black', ColorType.STANDARD, number=0), dim=True),
# 'markdown.block_quote': Style(color=Color('magenta', ColorType.STANDARD, number=5)),
# 'markdown.list': Style(color=Color('cyan', ColorType.STANDARD, number=6)),
# 'markdown.item': Style(),
# 'markdown.item.bullet': Style(color=Color('yellow', ColorType.STANDARD, number=3), bold=True),
# 'markdown.item.number': Style(color=Color('yellow', ColorType.STANDARD, number=3), bold=True),
# 'markdown.hr': Style(color=Color('yellow', ColorType.STANDARD, number=3)),
# 'markdown.h1.border': Style(),
# 'markdown.h1': Style(bold=True),
# 'markdown.h2': Style(bold=True, underline=True),
# 'markdown.h3': Style(bold=True),
# 'markdown.h4': Style(bold=True, dim=True),
# 'markdown.h5': Style(underline=True),
# 'markdown.h6': Style(italic=True),
# 'markdown.h7': Style(dim=True, italic=True),
# 'markdown.link': Style(color=Color('bright_blue', ColorType.STANDARD, number=12)),
# 'markdown.link_url': Style(color=Color('blue', ColorType.STANDARD, number=4))
