add_newline=false
format = """\
$username\
$hostname\
$directory\
$hg_branch\
$git_branch\
$git_commit\
$git_status\
$git_state\
$package\
$python\
$conda\
$docker_context\
$golang\
$julia\
$rust\
$cmd_duration\
$jobs\
$custom\
$character\
"""

[username]
format="[$user ]($style)"
style_root="cyan"
style_user="green"

[hostname]
format="[$hostname ](bright-blue)"
ssh_only=true
trim_at="."

[directory]
format="[$read_only](red)[$path ](bright-yellow)"
read_only="!"
truncation_length=4
truncate_to_repo=false
fish_style_pwd_dir_length=3

[hg_branch]
format="[$branch ](bold bright-white)"

[git_branch]
format="[$branch ](bold bright-white)"

[git_commit]
format="[$hash ](bright-black)"
commit_hash_length=7
only_detached=true

[git_state]
format="[$state $progress_current/$progress_total ](bold green)"
rebase="REBASE"
merge="MERGE"
revert="REVERT"
cherry_pick="CHERRY-PICK"
bisect="BISECT"

[git_status]
format="([$all_status$ahead_behind](bright-white) )"
conflicted="[$count!](bright-red)"
diverged="[${ahead_count}+${behind_count}-](bright-cyan)"
ahead="[${count}+](bright-cyan)"
behind="[${count}-](bright-cyan)"
untracked="$count?"
stashed="[${count}S](bright-red)"
modified="${count}m"
staged="${count}s"
renamed="${count}r"
deleted="[${count}D](bright-red)"

[package]
format="[$version ](bright-white)"

[python]
format="[$version ](italic bright-white)"
version_format="${raw}"
detect_extensions = []

[conda]
format="[$environment ](italic bright-white)"

[docker_context]
format="[docker $context ](bright-white)"
only_with_files=true

[golang]
format="[$version ](bright-white)"

[julia]
format="[$version ](bright-white)"

[rust]
format="[$version ](bright-white)"

[cmd_duration]
format="[$duration ](yellow)"
min_time=1000

[jobs]
format="[&$number ](bold yellow)"
threshold = 1

[custom.nvim]
command = "echo -n NVIM"
when = """test -n "$NVIM_LISTEN_ADDRESS" """

[character]
format="$symbol"
success_symbol="[\n\\$ ](bright-green)"
error_symbol="[\n\\$ ](bright-red)"
vicmd_symbol="[ VI-MODE \n\\$ ](bold fg:black bg:yellow)"
