#!/usr/bin/env bash
set -e

OS=$(cat /etc/os-release | grep "^ID=" | sed -e 's/ID=//' | sed -e 's/"//')
[ "$OS" != "ubuntu" ] && echo "Not a Ubuntu system; quiting" && exit 1

sudo apt -y update
sudo apt -y upgrade

sudo apt-add-repository -y ppa:fish-shell/release-3
sudo apt -y install curl direnv fish git

#sudo apt install -y --no-install-recommends pipx git ca-certificates python3 python3-venv \
#    libgl1 libxkbcommon-x11-0 libegl1-mesa libfontconfig1 libglib2.0-0 libdbus-1-3 \
#    libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libnss3 libxcomposite1 \
#    libxdamage1 libxrender1 libxrandr2 libxtst6 libxi6 libasound2
